server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:7901/eureka/
spring:
  application:
    name: consumer
  zipkin:
    base-url: http://localhost:9411/
  redis:
    host: localhost
    port: 6379
    timeout: 2000
logging:
  level:
    org.springframework: DEBUG
